version: '3.5'

services:
  backend:
    container_name: backend
    image: backend:1.0.0
    build:
      context: ./
      dockerfile: backend/Dockerfile
    volumes:
      - /home/felipe/Downloads:/app/images
    entrypoint: /usr/local/bin/python
    command: [backend.py]

  ui:
    container_name: interface
    image: interface:1.0.0
    build:
      context: ./
      dockerfile: interface/Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/felipe/Downloads:/app/images
    environment:
      - DISPLAY=${DISPLAY}
    entrypoint: /usr/local/bin/python
    command: [interface.py]