version: '3.5'

services:
  backend:
    container_name: backend
    image: backend:1.0.0
    build:
      context: ./
      dockerfile: app/backend/Dockerfile
    volumes:
      - /Users/felipe/Downloads:/app/images
    command: [python, backend.py]

  ui:
    container_name: interface
    image: interface:1.0.0
    build:
      context: ./
      dockerfile: app/ui/Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /Users/felipe/Downloads:/app/images
    environment:
      - DISPLAY=192.168.1.3:0
    command: [python, uy.py]